{"uuid": "a361ac66-f1ad-4bd3-aee8-1eb7069a4c20", "children": ["58389bb7-23c0-40d2-ab05-b955cd51982d"], "befores": [{"name": "appiumdriver", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102b5a2f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/_pytest/fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/_pytest/fixtures.py\", line 877, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/lekhraj/StudentAndroidApp/StudentAndroidApp/Testcases/conftest.py\", line 37, in appiumdriver\n    driver = webdriver.Remote(\"http://127.0.0.1:4723\", options=option)\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/appium/webdriver/webdriver.py\", line 229, in __init__\n    super().__init__(\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/selenium/webdriver/remote/webdriver.py\", line 238, in __init__\n    self.start_session(capabilities)\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/appium/webdriver/webdriver.py\", line 319, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/selenium/webdriver/remote/remote_connection.py\", line 391, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/selenium/webdriver/remote/remote_connection.py\", line 415, in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/urllib3/_request_methods.py\", line 144, in request\n    return self.request_encode_body(\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/urllib3/_request_methods.py\", line 279, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/urllib3/poolmanager.py\", line 444, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/urllib3/connectionpool.py\", line 877, in urlopen\n    return self.urlopen(\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/urllib3/connectionpool.py\", line 877, in urlopen\n    return self.urlopen(\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/urllib3/connectionpool.py\", line 877, in urlopen\n    return self.urlopen(\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/urllib3/connectionpool.py\", line 847, in urlopen\n    retries = retries.increment(\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/urllib3/util/retry.py\", line 515, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n"}, "start": 1732374753464, "stop": 1732374753465}], "start": 1732374753464, "stop": 1732374753537}