{"uuid": "c13759d1-c705-4eb2-962a-8fcfc724de72", "children": ["d848e88c-f14b-44c5-8e2f-c215b24b4476"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1732374220038, "stop": 1732374220038}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/lekhraj/Library/Python/3.10/lib/python/site-packages/_pytest/fixtures.py\", line 893, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/lekhraj/StudentAndroidApp/StudentAndroidApp/Testcases/conftest.py\", line 48, in log_on_failure\n    if item.rep_call.failed:\n"}, "start": 1732374222773, "stop": 1732374222773}], "start": 1732374220038, "stop": 1732374222773}